name: test

#on: push
on:
  push:
    branches-ignore:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install dependencies
        run: composer install

      - name: set laravel env
        run: echo "${{ secrets.LARAVEL_ENV }}" > .env

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.5.2
        with:
          node-version: v18.15.0

      - name: npm setup
        run: npm install

      - name: npm build
        run: npm run build

      - name: run unit test
        run: vendor/bin/phpunit tests/
